# Generated by Django 5.1.1 on 2025-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="Phone Number"),
                ),
                ("code", models.PositiveSmallIntegerField()),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
